rsync -rv ../intellij_for_aion/.idea/ ../rev_aion/.idea/
cp ../intellij_for_aion/aion_fastvm/modFastVM/modFastVM.iml ../rev_aion/aion_fastvm/modFastVM/modFastVM.iml
cp ../intellij_for_aion/aion_api/modAionApi.iml ../rev_aion/aion_api/modAionApi.iml
cp ../intellij_for_aion/modAionBase/modAionBase.iml ../rev_aion/modAionBase/modAionBase.iml
cp ../intellij_for_aion/modAionImpl/modAionImpl.iml ../rev_aion/modAionImpl/modAionImpl.iml
cp ../intellij_for_aion/modAion/modAion.iml ../rev_aion/modAion/modAion.iml
cp ../intellij_for_aion/modApiServer/modApiServer.iml ../rev_aion/modApiServer/modApiServer.iml
cp ../intellij_for_aion/modBoot/modBoot.iml ../rev_aion/modBoot/modBoot.iml
cp ../intellij_for_aion/modCrypto/modCrypto.iml  ../rev_aion/modCrypto/modCrypto.iml
cp ../intellij_for_aion/modDbImpl/modDbImpl.iml ../rev_aion/modDbImpl/modDbImpl.iml
cp ../intellij_for_aion/modEvtMgrImpl/modEvtMgrImpl.iml ../rev_aion/modEvtMgrImpl/modEvtMgrImpl.iml
cp ../intellij_for_aion/modEvtMgr/modEvtMgr.iml ../rev_aion/modEvtMgr/modEvtMgr.iml
cp ../intellij_for_aion/modLogger/modLogger.iml ../rev_aion/modLogger/modLogger.iml
cp ../intellij_for_aion/modMcf/modMcf.iml ../rev_aion/modMcf/modMcf.iml
cp ../intellij_for_aion/modP2pImpl/modP2pImpl.iml ../rev_aion/modP2pImpl/modP2pImpl.iml
cp ../intellij_for_aion/modP2p/modP2p.iml ../rev_aion/modP2p/modP2p.iml
cp ../intellij_for_aion/modRlp/modRlp.iml ../rev_aion/modRlp/modRlp.iml
cp ../intellij_for_aion/modTxPoolImpl/modTxPoolImpl.iml ../rev_aion/modTxPoolImpl/modTxPoolImpl.iml
cp ../intellij_for_aion/modTxPool/modTxPool.iml ../rev_aion/modTxPool/modTxPool.iml
cp ../intellij_for_aion/modPrecompiled/modPrecompiled.iml ../rev_aion/modPrecompiled/modPrecompiled.iml
cp ../intellij_for_aion/modGui/modGui.iml ../rev_aion/modGui/modGui.iml
cp ../intellij_for_aion/modVM/modVM.iml ../rev_aion/modVM/modVM.iml
